### PR TITLE
Remove the use of before_first_request

### PR DESCRIPTION
**Pull request by greyli**
This decorator has been removed in Flask 3.0.

### CODE REVIEW

**Review by macnewbold — APPROVED** [review]
These changes look good to me, and make sense. Is this compatible with all of our supported versions of Flask, or does this mean Flask 2.x will no longer work?

**Comment by jeffwidman** [comment]
Great question.

FWIW, if it's painful to retain backwards compatibility, don't be afraid to also drop support for Flask < 3.x. Most of those users will be fine with the older releases of `Flask-DebugToolbar`, and the ones who are currently broken are on newer Flask. Plus given the limited maintenance time this project receives, better to fix forward and start from a cleanish slate if needed. Whatever seems better to you two.

**Comment by greyli** [comment]
This change won't break the Flask 2.x and Flask 1.x compatibility.

**Comment by greyli** [comment]
Merged. I updated the test database URL to the in-memory SQLite database so that it will work on Windows.

**Pull request merged**
