### PR TITLE
Memory profiler

### PR DESCRIPTION
**Pull request by evoloshchuk**
New panel for memory debugging using Pympler. Disabled by default, slows down execution.

New config variable:
DEBUG_TB_PROFILER_MEMORY_ENABLED - enables memory profiling, Disabled by default.

### CODE REVIEW

**Comment by rimvislt** [comment]
Is anything similar on the plan to introduce into debug toolbar? This looks very good metric to track especially if it will work with ajax calls too.

**Comment by jeffwidman** [comment]
No one is actively working on this, but it's open source and as a maintainer I'm open to the feature if you want to put up a PR.

Given how dated this PR is, you probably want to start fresh as the python profiling tools have probably advanced a lot since 2012...

**Comment by macnewbold** [comment]
I know it's been a long time, but do you still have any interest in this?
If so, it will need to catch it up with master and retest. If not, we'll probably close it out.

**Comment by rimvislt** [comment]
I am still looking into this and once I have a bit of time, I will come back to either reuse what was submitted here or create something new that does similar.

**Pull request closed without merging**
