### PR TITLE
Take full advantage of pytest, add missing requirements to setup.py.

### PR DESCRIPTION
**Pull request by nfvs**
By taking full advantage of pytest fixtures, besides simplifying the
creation of Flask apps we can also pass config overrides to the app, so
we can test multiple cases without creating different apps.

We can now also run the tests with `python setup.py test`, which will
install the test requirements before running them.

Unit tests require SQL ALchemy to run, so they're now installed before
they're executed; `pip install .[tests]` should also install them manually.

### CODE REVIEW

**Comment by nfvs** [comment]
Happy to discuss this, but it shouldn't break running the tests with tox.

The reason to use fixtures is to allow for different tests to use different configurations and different initialization parameters; for example, I'm interested in adding support for a callback specified on `__init__` (or `init_app()`) that allows us to override the decision to display the toolbar or not. My use case is to display the toolbar only for certain users, instead of displaying to everyone.

**Comment by nfvs** [comment]
Added a couple of tests (toolbar disabled, and no secret key) as an example of how powerful pytest fixtures are, and how easily it enables us to configure individual tests.

**Comment by jeffwidman** [comment]
👍 for this, I'm a big `pytest` fan myself.

I know you opened this a while ago, are you still interested in driving this to completion?

If so, can you rebase and then I'll review?

**Comment by nfvs** [comment]
Seems like too much has changed, feel free to take it over.

**Comment by jeffwidman** [comment]
No problem, I'm going to re-open so I don't lose track of it.

**Comment by macnewbold** [comment]
I know more and more time keeps going by on this one... what's the current status? I agree that getting the test support would be helpful.

**Comment by macnewbold** [comment]
I'm going to close this for now, until someone wants to adopt it and get it updated and tested. Sounds like currently nobody has time for it, but some day maybe that will change. Thanks!

**Pull request closed without merging**
